BlueOath/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BlueOath.Data;
using BlueOath.Models;
using Microsoft.AspNetCore.Authorization;

namespace BlueOath.Controllers
{
    [Authorize]
    public class RoomsController : Controller
    {
        private readonly BlueOath.Areas.Identity.Data.BlueOathContext _identityContext;
        private readonly IWebHostEnvironment _hostEnvironment;

        public RoomsController(BlueOath.Areas.Identity.Data.BlueOathContext context1, IWebHostEnvironment hostEnvironment)
        {
            _identityContext = context1;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
              return _identityContext.Room != null ? 
                          View(await _identityContext.Room.ToListAsync()) :
                          Problem("Entity set 'BlueOathContext.Room'  is null.");
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _identityContext.Room == null)
            {
                return NotFound();
            }

            var room = await _identityContext.Room
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RoomType,Facilities,RoomImage,Rate,Status")] Room room)
        {
            if (ModelState.IsValid)
            {
                //Save image to wwwroot/image
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(room.RoomImage.FileName);
                string extension = Path.GetExtension(room.RoomImage.FileName);
                room.Description = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await room.RoomImage.CopyToAsync(fileStream);
                }
                _identityContext.Add(room);
                await _identityContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _identityContext.Room == null)
            {
                return NotFound();
            }

            var room = await _identityContext.Room.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RoomType,Facilities,Description,Rate,Status")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _identityContext.Update(room);
                    await _identityContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _identityContext.Room == null)
            {
                return NotFound();
            }

            var room = await _identityContext.Room
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_identityContext.Room == null)
            {
                return Problem("Entity set 'BlueOathContext.Room'  is null.");
            }
            var room = await _identityContext.Room.FindAsync(id);
            //delete image from wwwroot/image
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "image", room.Description);

            if (System.IO.File.Exists(imagePath))
                System.IO.File.Delete(imagePath);
            //delete the record
            _identityContext.Room.Remove(room);

            if (room != null)
            {
                _identityContext.Room.Remove(room);
            }
            
            await _identityContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
          return (_identityContext.Room?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BlueOath/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlueOath</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <header class="m-auto bg-info-subtle border-bottom">
        <ul class="nav nav-underline py-3 ps-5">
            <li class="nav-item display-6 px-3">
                <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">BlueOath</a>
            </li>
            <li class="nav-item px-3 h2">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Menu">Home</a>
            </li>
            <li class="nav-item px-3 h2">
                <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
            </li>
            <partial name="_LoginPartial" />
        </ul>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center bg-info-subtle p-3 fixed-bottom">
        <div class="container">
            &copy; 2023 - BlueOath, Inc 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>